version: '3'

services:

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    networks:
      - node-network
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: fullcyclerichieri/nginx:prod
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
